### ISSUE TITLE
Option for Background-Images?

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-teaser#7]
In den Templates (z.B. linkteaser_content_image_above.html5) finde ich eine Abfrage der Variable $this->background, die ggf. dafür sorgt, dass ein Bild per Inline-Style als Hintergrund ausgegeben wird.
Aber findet man diese Option auch im Contao-Backend?

**Comment by fatcrobat** [comment]
Hallo,

wir haben das im Teaser Modul nicht am DatenContainer von tl_content hintergelt sondern mit unserer Erweiterung heimrichhannot/contao-bootstrapper realisiert. Gern kannst du einen Pull Request einreichen in dem das Datenbankfeld in tl_content des Moduls heimrichhannot/contao-teaser liegt.

**Comment by rustykowski** [comment]
Danke für die Info!
Bin leider kein Entwickler. Einen Pull-Request werde daher nicht selbst einreichen können.
